### ISSUE TITLE
Laravel 5.1 Support

### ISSUE THREAD

**Issue by tylerr92** [GlueDev/laravel-stackdriver#1]
Hello,

I noticed you require Laravel 5.7 or newer. I was wondering if this was done on purpose and if you had any interest in trying to allow for Laravel 5.1. Thank you.

**Comment by DiederikvandenB** [comment]
Sorry for the late response. Laravel 5.1 is not supported because this package was created way after that release. I am personally not interested in supporting older versions, but I will accept PRs introducing this support.
