### ISSUE TITLE
_ENABLED vars can end up bring strings and failing strict checks

### ISSUE THREAD

**Issue by addshore** [GlueDev/laravel-stackdriver#14]
I spent a while trying to set this up and ended up realizing that I was caught on some strict bool checks for the enabled settings in StackdriverExceptionHandler

```
        if (config('stackdriver.enabled') === false || config('stackdriver.error_reporting.enabled') === false) {
            return;
        }
```

I resolve this for me for now by casting these to cool in my settings file.

`        'enabled' => (bool)env('STACKDRIVER_ERROR_REPORTING_ENABLED', true),
`

I want to make a PR to make sure no one else falls over this issue but would like to know if I should go for casting the settings to bool or switching to non strict comparisons when the config is checked.

**Comment by DiederikvandenB** [comment]
This is very weird. Laravel should cast env settings correctly. See:
https://github.com/laravel/framework/blob/2e4d634b913e8c747721b830f2e7b03e0bf30b3e/src/Illuminate/Support/Env.php#L79-L108.

Can you show me your .env file?
