### ISSUE TITLE
Laravel best practices

### ISSUE THREAD

**Issue by maikealame** [GlueDev/laravel-stackdriver#2]
Hi,

Thanks for the great package. I just see the main Readme, maybe I talk bullshit here, ignore them if so.
It can be used in logging.php, created since v5.6 ? In that file I can combine many loggings providers for each environment, without making a flag inside a specific config file 'stackdriver.php'.

Something like this:
https://medium.com/binarcode/laravel-5-6-custom-monolog-channel-to-store-logs-in-mariadb-23da52f537e7

**Comment by DiederikvandenB** [comment]
In theory, it would be possible to implement it as you suggested. However, not everything this package does has to do with logging (tracing and error reporting are fundamentally different), so we'd have to place those configs in separate files. Therefore we chose a package specific config file.

**Comment by maikealame** [comment]
Very explained, I think now mixing different things in this case is no good. Thanks
