### ISSUE TITLE
Show the exception message

### ISSUE THREAD

**Issue by BadChoice** [GlueDev/laravel-stackdriver#3]
Currently it only shows the exception but not the message, and this is something that can really help figure out what is happening,

Could it be possible to add?
I can try create a PR if you give me a couple of hints on where to add it

Thanks!

**Comment by DiederikvandenB** [comment]
I am not sure I follow. What part of the exception exactly are you missing?

```php

Route::get('/', function () {
    $error = 'Testing Stackdriver';
    $time = Carbon::now()->toDateTimeString();
    $message = join(' ', [$error, $time]);
    
    throw new Exception($message);
});
```

The code above shows up like this in my Cloud Console:
![image](https://user-images.githubusercontent.com/6132723/64850326-7c534500-d615-11e9-9d48-33400d8a7937.png)

As you can see, the message is definitely visible for me. Furthermore, there's little influence I have over how Google shows the data it gets passed. As you can see on [this line of code](https://github.com/GlueDev/laravel-stackdriver/blob/develop/src/StackdriverExceptionHandler.php#L44), the exception as a whole is passed on to Google.

Let me know if this is enough information for you.

**Comment by BadChoice** [comment]
So weird, 
for example a NotFoundException, I can't see the URL that is not found 

<img width="1433" alt="Captura de Pantalla 2019-09-13 a les 12 01 57" src="https://user-images.githubusercontent.com/93900/64854623-58e0c800-d61e-11e9-84e1-5db87af0abfd.png">

**Comment by DiederikvandenB** [comment]
![image](https://user-images.githubusercontent.com/6132723/64859798-85e7a780-d62b-11e9-8a5a-aeb828ff1827.png)

Apparently, Laravel throws a not found exception without a message attached to it. This is behaviour you could override in your `app/Exceptions/Handler.php`. However, that is outside of the scope of this package. As long as your exception has a message, the message should appear in your Cloud Console.

For now, I am closing this issue.

**Comment by BadChoice** [comment]
Ohh I see,
We used to use rollbar before migrating to goggle and we had kind of more info there, but as you say, this is not because of this package

Thank you so much for it, it works really well

Best!
