### ISSUE TITLE
breaking change on laravel 7

### ISSUE THREAD

**Issue by ibrunotome** [GlueDev/laravel-stackdriver#9]
Laravel 7 now receives a Throwable instead of Exception in `public function report(Throwable $exception)`

the `public static function report(Exception $exception): void` expects the Exception type.

What we can do? bump a new major version for laravel 7 compatibility or remove the type of variable?

**Comment by DiederikvandenB** [comment]
I’ll have a look this afternoon. Thanks for reporting!

**Comment by DiederikvandenB** [comment]
I decided to drop the type so we can keep backwards compatibility.

Released `v0.2.1`
